"""Write reports/virgintrains_eda.md from the pipeline outputs (numbers are computed, not typed).

Run after build_virgintrains.py, discover_intents.py, prepare_splits.py, generate_taxonomy.py.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from collections import Counter
from itertools import combinations
from pathlib import Path

import _bootstrap  # noqa: F401
import pandas as pd
import yaml

from common.logging_utils import configure_logging
from evaluation.sampling import length_bucket
from ingestion.resolution_signals import display_text
from ingestion.text import template_key

logger = logging.getLogger("virgintrains_report")


def pct(x: float, digits: int = 1) -> str:
    return f"{100 * x:.{digits}f}%"


def table(headers: list[str], rows: list[list]) -> str:
    numeric = [all(re.fullmatch(r"[\d,.]+%?", str(r[i])) for r in rows) for i in range(len(headers))]
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---:" if numeric[i] else "---" for i in range(len(headers))) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def clip(text: str, n: int = 200) -> str:
    text = " ".join(str(text).split()).replace("|", "\\|")
    return text if len(text) <= n else text[: n - 1] + "…"


def top_patterns(cases: pd.DataFrame, n: int = 12) -> list[tuple[str, int, str]]:
    keyed: dict[str, list[str]] = {}
    for msgs in cases["agent_messages"]:
        if len(msgs):
            key = template_key(msgs[0], 6).replace("we're", "we are")
            if key:
                keyed.setdefault(key, []).append(msgs[0])
    ranked = sorted(keyed.items(), key=lambda kv: -len(kv[1]))[:n]
    return [(k, len(v), clip(display_text(Counter(v).most_common(1)[0][0]), 150)) for k, v in ranked]


def evidence_patterns(cases: pd.DataFrame, signal: str, n: int = 3) -> list[tuple[int, str]]:
    snippets = [e["snippet"] for ev in cases["resolution_evidence"] for e in ev if e["signal"] == signal]
    keyed: dict[str, list[str]] = {}
    for s in snippets:
        keyed.setdefault(template_key(s, 6), []).append(s)
    ranked = sorted(keyed.items(), key=lambda kv: -len(kv[1]))[:n]
    return [(len(v), clip(Counter(v).most_common(1)[0][0], 150)) for _, v in ranked]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--processed-dir", type=Path, default=_bootstrap.DEFAULT_PROCESSED)
    parser.add_argument("--reports-dir", type=Path, default=_bootstrap.REPO_ROOT / "reports")
    parser.add_argument("--taxonomy", type=Path, default=_bootstrap.REPO_ROOT / "configs" / "virgintrains_intents.yaml")
    parser.add_argument("--log-level", default="INFO")
    args = parser.parse_args()
    configure_logging(args.log_level)
    p = args.processed_dir

    tweets = pd.read_parquet(p / "virgintrains_tweets.parquet")
    cases = pd.read_parquet(p / "virgintrains_cases.parquet")
    convs = pd.read_parquet(p / "virgintrains_conversations.parquet", columns=["conversation_id", "tweet_count", "case_count", "max_gap_hours", "has_missing_parent"])
    build = json.loads((p / "virgintrains_build_report.json").read_text(encoding="utf-8"))
    manifest = json.loads((p / "splits" / "virgintrains_split_manifest.json").read_text(encoding="utf-8"))
    clusters = json.loads((p / "virgintrains_intent_clusters.json").read_text(encoding="utf-8"))
    preview = json.loads((p / "virgintrains_cluster_preview.json").read_text(encoding="utf-8"))
    taxonomy = yaml.safe_load(args.taxonomy.read_text(encoding="utf-8"))["taxonomy"]
    assign = pd.read_csv(p / "splits" / "virgintrains_split_assignments.csv")
    cases = cases.merge(assign[["case_id", "split", "cluster_id"]], on="case_id")
    train = cases[cases["split"] == "train_retrieval"]

    seg, filt = build["segmentation"], build["filter"]
    n_tweets, n_convs, n_cases = len(tweets), len(convs), len(cases)
    role_counts = tweets["role"].value_counts().to_dict()
    with_reply = cases["has_brand_reply"]
    L: list[str] = []
    add = L.append

    add("# VirginTrains EDA: from raw tweets to candidate intents\n")
    add("Generated by `scripts/virgintrains_report.py`; every number below is computed from `data/processed/`. "
        "All labels (resolution types, intent clusters) are **heuristic or unsupervised** and not ground truth.\n")

    add("## 1. Volume\n")
    add(table(["measure", "value"], [
        ["Conversations in full dataset", f"{filt['conversations_total']:,}"],
        ["Conversations involving VirginTrains (it authored >= 1 tweet)", f"{n_convs:,}"],
        ["Tweets in those conversations", f"{n_tweets:,}"],
        ["... customer / VirginTrains agent / other-operator agent tweets", f"{role_counts.get('customer', 0):,} / {role_counts.get('brand_agent', 0):,} / {role_counts.get('other_agent', 0):,}"],
        ["Tweets not attributed to any case (brand-initiated or unattributable)", f"{seg['unattributed_tweets']:,}"],
        ["Support cases (one per customer episode)", f"{n_cases:,}"],
        ["... continuation cases (same customer resuming after > {} h)".format(build["gap_hours"]), f"{seg['continuation_episodes']:,}"],
        ["Cases with a VirginTrains reply", f"{int(with_reply.sum()):,} ({pct(with_reply.mean())})"],
        ["Date range of tweets", f"{tweets['created_at'].min():%Y-%m-%d} to {tweets['created_at'].max():%Y-%m-%d}"],
        ["Share of tweets from 2017-10-09 onward", pct((tweets['created_at'] >= '2017-10-09').mean())],
    ]))
    add("\nWeekly case volume (by first timestamp):\n")
    weekly = cases["first_timestamp"].dt.tz_convert(None).dt.to_period("W-SUN").dt.start_time.dt.strftime("%Y-%m-%d")
    wk = weekly.where(cases["first_timestamp"] >= "2017-10-09", "before 2017-10-09").value_counts().sort_index()
    add(table(["week starting", "cases"], [[k, f"{v:,}"] for k, v in wk.items()]))

    add("\n## 2. Thread and episode structure\n")
    add(table(["measure", "value"], [
        ["Multi-customer threads (more than one customer replies in the thread)", f"{seg['multi_customer_conversations']:,}"],
        ["Threads split into >1 case beyond customer split (time gap)", f"{seg['conversations_split']:,}"],
        ["Orphan tweets linked by mention", f"{seg['orphans_linked']:,}"],
        ["Owner attribution of tweets", ", ".join(f"{k}: {v:,}" for k, v in seg['owner_sources'].items())],
        ["Inbound-flagged accounts treated as agents", ", ".join(build['hidden_agents'])],
    ]))
    add("\n### Turn distribution (turns per case)\n")
    tc = cases["turn_count"]
    buckets = cases["turn_count"].map(length_bucket).value_counts()
    add(table(["bucket", "cases", "share"], [[b, f"{buckets.get(b, 0):,}", pct(buckets.get(b, 0) / n_cases)] for b in ["short_1-2", "medium_3-4", "long_5-8", "very_long_9+"]]))
    add(f"\nmean {tc.mean():.2f}, median {tc.median():.0f}, p90 {tc.quantile(.9):.0f}, p99 {tc.quantile(.99):.0f}, max {tc.max()}. "
        f"Customer turns/case mean {cases['customer_turn_count'].mean():.2f}; agent turns/case mean {cases['agent_turn_count'].mean():.2f}. "
        f"Median first-response time {cases['first_response_minutes'].median():.0f} min (p90 {cases['first_response_minutes'].quantile(.9):.0f} min).\n")

    add("## 3. Resolution (rule-based, observable behaviour only)\n")
    add(f"Resolved (customer thanked/confirmed or agent closed the thread): **{pct(cases['resolved'].mean())}**. "
        f"DM redirect (any agent turn asks to move to DM): **{pct(cases['dm_redirect'].mean())}** of all cases, "
        f"{pct(cases.loc[with_reply, 'dm_redirect'].mean())} of cases with an agent reply. "
        "Resolution that happens in DMs, by phone, or in person is invisible here, so the resolved rate is a lower bound.\n")
    rt = cases.groupby("resolution_type").agg(cases=("case_id", "size"), resolved=("resolved", "mean"), dm=("dm_redirect", "mean"), turns=("turn_count", "mean")).sort_values("cases", ascending=False)
    add(table(["resolution_type", "cases", "share", "% resolved", "% DM", "avg turns"], [
        [k, f"{int(r.cases):,}", pct(r.cases / n_cases), pct(r.resolved), pct(r.dm), f"{r.turns:.1f}"] for k, r in rt.iterrows()]))
    oc = cases["resolution_outcome"].value_counts()
    add("\nHow threads ended (outcome label): " + ", ".join(f"{k} {pct(v / n_cases)}" for k, v in oc.items()) + ".\n")

    add("### Top recurring resolution patterns (first agent reply, train split)\n")
    add(table(["count", "normalized prefix", "example"], [[c, f"`{k}`", e] for k, c, e in top_patterns(train)]))
    add("\nMost frequent evidence phrases behind selected resolution types (train split):\n")
    for sig in ["compensation", "self_service", "redirected_to_dm", "redirected_to_other_operator", "escalated", "troubleshooting"]:
        pats = evidence_patterns(train, sig)
        add(f"- **{sig}**: " + "; ".join(f'{c}x "{t}"' for c, t in pats))

    add("\n## 4. Candidate intents (unsupervised, from opening messages)\n")
    add(f"{preview['n_fit']:,} openers (train+dev customers; entities masked), embeddings `{preview['embedding_model']}`, KMeans k={preview['k']}. "
        f"{preview['n_insufficient_or_continuation']:,} cases have no usable opening (too little text, or continuation episode) and sit outside the clusters.\n")
    sweep = preview["k_sweep"]
    k_row = next(r for r in sweep if r["k"] == preview["k"])
    add(table(["k", "silhouette (cosine)", "seed agreement (ARI)", "smallest cluster"], [
        [r["k"], f"{r['silhouette']:.3f}", f"{r['seed_agreement_ari']:.2f}", pct(r["min_cluster_share"])] for r in sweep]))
    add(f"\nSilhouette is low everywhere (<= {max(r['silhouette'] for r in sweep):.3f}): topics overlap heavily in short tweets, so these are soft partitions. "
        f"Clusterings are reproducible across seeds (ARI {k_row['seed_agreement_ari']:.2f} for the chosen k) but only weakly agree with an independent TF-IDF/LSA clustering "
        f"(NMI {preview['tfidf_agreement']['nmi']:.2f}, ARI {preview['tfidf_agreement']['ari']:.2f}), so boundaries between neighbouring clusters should not be over-interpreted. "
        "A first attempt without entity masking clustered by route (Euston/Manchester vs London/Glasgow) rather than intent; masking places, times and seat references fixed that.\n")
    add(table(["id", "candidate intent", "cases", "share", "% resolved", "% DM", "recommended final intent"], [
        [c["cluster_id"], c["proposed_intent_name"], f"{c['n_cases']:,}", pct(c["share_of_clustered"]), pct(c["pct_resolved"]), pct(c["pct_dm_redirect"]), c["recommended_final_intent"]]
        for c in sorted(clusters, key=lambda x: -x["n_cases"])]))
    add("\nFull per-cluster detail (examples, confusable neighbours, patterns): `reports/virgintrains_intent_clusters.md`.\n")

    add("## 5. Ambiguous and difficult cases\n")
    add("### Low-margin openers (nearly equidistant from two clusters)\n")
    shown = 0
    for c in sorted(clusters, key=lambda x: -x["n_cases"]):
        for e in c["ambiguous_examples"][:1]:
            add(f"- `{e['case_id']}` (cluster {c['cluster_id']} {c['proposed_intent_name']}, also close to {e['also_close_to']}): {clip(e['text'], 230)}")
            shown += 1
    add("\n### Resolution labels that are hard to trust\n")
    cols = ["case_id", "opening_message", "resolution_type", "resolution_outcome", "resolution_summary"]
    probes = {
        "Agent asked for DM yet the thread ended with the customer thanking them (resolved and DM redirect)": cases[cases["resolved"] & cases["dm_redirect"]],
        "Compensation/refund discussed but the customer's last follow-up went unanswered": cases[cases["resolution_type"].isin(["compensation", "refund"]) & (cases["resolution_outcome"] == "customer_followup_unanswered")],
        "Customer talks to another operator's agent inside the VirginTrains thread": cases[cases["other_agent_turn_count"] > 0],
        "Very long multi-turn cases (mixed topics within one episode)": cases[cases["turn_count"] >= 20],
    }
    for title, sub in probes.items():
        add(f"**{title}** ({len(sub):,} cases). Examples:\n")
        for r in sub.sort_values("case_id").head(2)[cols].itertuples():
            add(f"- `{r.case_id}` opening: {clip(r.opening_message or '', 160)}  \n  _{clip(r.resolution_summary, 260)}_")
        add("")

    add("## 6. Data quality issues\n")
    agent_tw = tweets[tweets["role"] == "brand_agent"]
    agent_missing_irt = agent_tw["in_response_to_tweet_id"].isna().mean()
    cust_tw = tweets[tweets["role"] == "customer"]
    cust_missing_irt = cust_tw["in_response_to_tweet_id"].isna().mean()
    tw_missing_resp = tweets["response_tweet_id_raw"].isna().mean()
    add("\n".join([
        f"- **Unreliable `inbound` flag**: {len(build['hidden_agents'])} accounts flagged `inbound=True` behave like other operators' agents (caret sign-offs). Treated as `other_agent`; raw flag preserved.",
        f"- **Missing relationship ids**: `in_response_to_tweet_id` is empty for {pct(cust_missing_irt)} of customer tweets (expected: thread openers) but also for {pct(agent_missing_irt)} of VirginTrains agent tweets (a real gap: replies whose parent is not recorded; `response_tweet_id` is empty for {pct(tw_missing_resp)} of all tweets). "
        f"Parent ids that point at tweets absent from the file: {int(tweets['missing_parent'].sum()):,} tweets. Every VirginTrains conversation has >= {int(convs['tweet_count'].min())} tweets (the dataset contains no single-tweet VirginTrains threads), so the @mention orphan-linking fallback attached {seg['orphans_linked']} tweets; it matters only for other brands.",
        f"- **Revived threads**: {seg['conversations_split']:,} threads contain a silence longer than {build['gap_hours']:.0f} h; {int((convs['max_gap_hours'] > 24 * 7).sum()):,} contain a gap longer than a week. {int((tweets['created_at'] < '2017-10-09').sum()):,} tweets pre-date 2017-10-09 (back to {tweets['created_at'].min():%Y}), i.e. people replying into old threads.",
        f"- **Multi-customer threads**: {seg['multi_customer_conversations']:,} threads contain several customers; they are split into one case per customer, but replies from a customer to another customer remain visible context only in the thread table.",
        f"- **Unattributed tweets**: {seg['unattributed_tweets']:,} agent tweets that answer nobody in the data (announcements, replies to tweets outside the sample) are excluded from cases; their ids are kept in the tweets table with `exclusion_reason`.",
        f"- **Cases without a brand reply**: {pct(1 - with_reply.mean())} (often customers replying to other customers under an announcement). {int((cases['customer_turn_count'] == 0).sum())} cases have no customer message at all.",
        f"- **Public view only**: {pct(cases['dm_redirect'].mean())} of cases show a DM request; anything resolved after that is not observable, so `resolved` and `redirected_to_dm` under-describe real handling.",
        "- **Heuristic labels**: resolution types come from regexes (e.g. `refund` = refund discussed, including denials; `compensation` includes any 'claim' wording). Precision has been spot-checked, not measured.",
        f"- **Weak cluster structure**: silhouette <= {max(r['silhouette'] for r in sweep):.2f} and low agreement with a TF-IDF clustering (see section 4).",
        "- **Templated brand replies**: a few canned replies ('we are awaiting an update as to when ...') account for much of the 'information_provided' mass, so reply-grounding metrics may reward template matching.",
        "- **Encoding**: stored text is untouched; only a handful of tweets contain genuinely corrupted characters (mojibake).",
        "- **Time window**: almost all tweets fall in a seven-week window around Oct-Dec 2017, so event-driven topics (a specific disruption week) are over-represented and temporal generalisation cannot be assessed.",
    ]))

    add("\n## 7. Evaluation splits\n")
    cnt = manifest["counts"]
    add(table(["split", "cases", "allowed use"], [[k, f"{cnt.get(k, 0):,}", manifest["usage_rules"].get(k, "")] for k in ["train_retrieval", "dev_calibration", "golden_eval", "golden_pool_reserve", "excluded_leakage_guard"]]))
    add(f"\nCases that share a customer or a conversation thread are grouped and hashed together (seed {manifest['config']['seed']}), so no customer or thread spans two splits. "
        f"Clusters were fit on train+dev only; golden candidates were stratified from the golden pool by cluster, resolution type, length, DM redirect and resolved flag "
        f"(stratified, **not** natural prevalence; `golden_stratum_weight` restores prevalence by cluster). Leakage checks (all must be 0): {manifest['leakage_checks_all_zero']}. "
        "Golden candidates are unlabelled until hand-labelled. Do not tune thresholds, prompts, or retrieval on them.\n")

    add("## 8. Recommended final taxonomy (8-12 intents)\n")
    add("Evidence-based, still **candidate**. It merges the three 'where is my train / what is the delay' clusters, because they share customer goal and the same canned agent replies, and keeps the rest as separate clusters.\n")
    intents = taxonomy["intents"] + ([taxonomy["fallback"]] if taxonomy.get("fallback") else [])
    add(table(["#", "intent", "cases", "% resolved", "% DM", "dominant resolution types", "auto-handle (NEEDS_REVIEW) hint"], [
        [i + 1, t["name"], f"{t['n_cases']:,}", pct(t["pct_resolved"] or 0), pct(t["pct_dm_redirect"] or 0),
         ", ".join(f"{k} {pct(v, 0)}" for k, v in list(t["resolution_types"].items())[:3]), t["auto_handle_evidence"]["hint"]]
        for i, t in enumerate(intents)]))
    by = {c["cluster_id"]: c for c in clusters}
    status = [c for c in clusters if c["recommended_final_intent"] == "service_status_delay_enquiry"]
    sets = {c["cluster_id"]: {p["template"] for p in c["representative_resolution_patterns"]} for c in status}
    overlaps = [f"{a}/{b}: {len(sets[a] & sets[b])} shared of top templates" for a, b in combinations(sets, 2)]
    add("\n**Why merge status/delay clusters:** " + "; ".join(overlaps) + ". Their resolution mix is the same (mostly `information_provided`, then `self_service` links to Live Updates).\n")
    add("**What to do about the weak spots before building on it:**\n")
    chat = next((t for t in intents if t["name"] == "chitchat_non_support"), None)
    if chat:
        add(f"- `chitchat_non_support` is **not** clean chit-chat: agents answered with substantive information in {pct(chat['resolution_types'].get('information_provided', 0), 0)} of its cases, "
            "and its low-margin examples include real complaints. Treat it as 'low-signal opener', not as 'safe to ignore'.")
    add("- `journey_disruption_complaint` is a catch-all with no clear question; expect noisy labels. Hand-label both catch-all clusters first in the golden set.")
    add("- `customer_service_complaint` and `delay_repay_refund_claim` have the highest DM-redirect rates; these are the best candidates for human escalation, but only a human reviewer can confirm that.")
    add("- No cluster separates lost property, accessibility assistance, or safety incidents; they are rare and hidden inside `journey_disruption_complaint`. Consider adding them as explicit escalation triggers rather than intents.")
    add("- `unclear_or_media_only` is a necessary fallback intent: some openers contain only a mention, photo, or link.")
    add("- `safe_to_auto_handle` is `NEEDS_REVIEW` for every intent. The hints above only say where historic agent behaviour is templated or low-risk, not that automation is safe.\n")

    path = args.reports_dir / "virgintrains_eda.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(L) + "\n", encoding="utf-8")
    logger.info("Wrote %s (%d lines)", path, len(L))


if __name__ == "__main__":
    main()
